on:
  release:
    types: [created]

jobs:
  release-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
        exclude:
          - goarch: arm64
            goos: windows
    steps:
    - uses: actions/checkout@v3
    - name: Get tags
      run: git fetch --tags origin
    - uses: wangyoucao577/go-release-action@v1
      with:
        pre_command: export CGO_ENABLED=0
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        binary_name: kra
        asset_name: kra-${{ matrix.goos }}-${{ matrix.goarch }}
        #extra_files: LICENSE README.md
